services:
  - type: web
    name: audio copyright detector
    env: python
    buildCommand: |
      apt-get update && apt-get install -y chromaprint-tools
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
